version: '3.8'

services:
  app:
    build: .  
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - DB_PATH=./data.db
    env_file:
      - .env  # Fix the incorrect .env mounting
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - db_data:/data

volumes:
  db_data:
